name: sartex_tv
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+19

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  uuid: ^3.0.6
  flutter_svg: ^0.20.0-nullsafety.3
  shared_preferences: ^2.0.15
  freezed: ^2.1.0
  json_annotation: ^4.6.0
  package_info_plus: ^1.4.3
  intl: ^0.17.0
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  fonts:
    - family: Agency FB
      fonts:
        - asset: assets/fonts/agencyfb_reg.ttf
    - family: NotoSansArmenian
      fonts:
        - asset: assets/fonts/NotoSansArmenianRegular.ttf
    - family: Sylfaen
      fonts:
        - asset: assets/fonts/Sylfaen.ttf

  assets:
    - assets/

